#! /bin/sh

sxhkd &
xsetroot -cursor_name left_ptr &
xsetroot -solid "#1d2323" &

bspc monitor -d 1 2 3 4

bspc config border_width         4
bspc config window_gap           8

bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc config focus_follows_pointer true
